name: xagent
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - jupyterlab
  - pip
  - pip:
    - scikit-learn==0.23.0
    - simcse==0.4
    - alibi==0.6.1
    - shap==0.40.0
    - openml==0.12.2
    - scipy==1.5.4
    - dtreeviz==1.3
    - graphviz==0.16
    - dice-ml==0.7.2
    - protobuf==3.17.3
    - anchor-exp==0.0.2.0
    - keras==2.6.0
    - tensorflow==2.5.0
    - spacy==3.1.4
    - numpy==1.19.5